Update connection.rb
The »place« wrapper fails if the order is deleted in another thread. This results in a #<NoMethodError: undefined method `place' for nil:NilClass>, which can easily be avoided.
Alternativley a rescue-cause is possible, too.